name: Deploy Vite

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 145.79.14.31
          username: u212616308
          password: ${{ secrets.HOSTINGER_PASS }}
          port: 21
          protocol: ftp
          local-dir: dist/
          server-dir: public_html/
          timeout: 120000
          log-level: verbose
          passive: true
          dangerous-clean-slate: false
